import { Dimensions, StyleSheet } from 'react-native';

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');

export const createStyles = (theme: any) =>
  StyleSheet.create({
  root: {
    flex: 1,
  },
  headerTabsWrapper: {
    position: 'relative',
    paddingTop: SCREEN_HEIGHT * 0.12,
    paddingHorizontal: 24,
    zIndex: 10,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    overflow: 'hidden',
  },
  headerTabsBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  logoWrapper: {
    alignItems: 'center',
    zIndex: 1,
    marginBottom: SCREEN_HEIGHT * 0.04,
  },
  bgWrapper: {
    flex: 1,
    width: '100%',
    position: 'relative',
  },
  bgSvg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
    zIndex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: SCREEN_HEIGHT < 700 ? 100 : 120,
    flexGrow: 1,
  },
  backButton: {
    position: 'absolute',
    top: SCREEN_HEIGHT * 0.06 + 10,
    left: 24,
    zIndex: 2,
  },
  backButtonCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
      backgroundColor: theme.card,
    justifyContent: 'center',
    alignItems: 'center',
      shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 0,
    borderBottomWidth: 1,
      borderBottomColor: theme.divider,
    zIndex: 1,
  },
  tab: {
    flex: 1,
    paddingBottom: 12,
    alignItems: 'center',
    position: 'relative',
  },
  tabUnderline: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    width: 134,
    height: 7,
    backgroundColor: theme.buttonPrimary,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  tabText: {
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 16 : 18,
    color: theme.textPrimary,
  },
  tabTextActive: {
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 16 : 18,
    color: theme.buttonPrimary,
  },
  loginWithSection: {
    marginTop: SCREEN_HEIGHT * 0.04,
    marginBottom: 24,
  },
  loginWithText: {
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 14 : 16,
    color: theme.textPrimary,
    marginBottom: 12,
    textAlign: 'center',
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.card,
    borderWidth: 1,
    borderColor: theme.divider,
    borderRadius: 30,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  googleIcon: {
    marginRight: 12,
  },
  googleButtonLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: SCREEN_HEIGHT < 700 ? 14 : 16,
    color: theme.textPrimary,
    textAlign: 'center',
  },
  formContainer: {
    flex: 1,
  },
  inputWrapper: {
    marginBottom: 10,
  },
  inputLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 14 : 16,
    color: theme.textPrimary,
    marginBottom: 8,
  },
  input: {
    backgroundColor: theme.inputBackground,
    borderRadius: 8,
    paddingVertical: SCREEN_HEIGHT < 700 ? 12 : 14,
    paddingHorizontal: 16,
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 14 : 16,
    color: theme.inputText,
    borderWidth: 0,
  },
  passwordInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.inputBackground,
    borderRadius: 8,
    borderWidth: 0,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: SCREEN_HEIGHT < 700 ? 12 : 14,
    paddingHorizontal: 16,
    fontFamily: 'Inter_500Medium',
    fontSize: SCREEN_HEIGHT < 700 ? 14 : 16,
    color: theme.inputText,
  },
  eyeIcon: {
    paddingRight: 16,
    paddingLeft: 8,
  },
  forgotPassword: {
    marginBottom: 16,
    alignSelf: 'flex-end',
  },
  forgotPasswordText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    color: theme.buttonPrimary,
  },
  passwordRequirements: {
    marginBottom: 16,
  },
  passwordRequirementsText: {
    fontFamily: 'Inter_300Light',
    fontSize: 12,
    color: theme.textSecondary,
    marginBottom: 8,
  },
  passwordStrengthContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordStrengthBar: {
    flex: 1,
    height: 4,
    backgroundColor: theme.divider,
    borderRadius: 2,
    marginRight: 12,
  },
  passwordStrengthFill: {
    height: '100%',
    width: '20%',
    backgroundColor: theme.buttonPrimary,
    borderRadius: 2,
  },
  passwordStrengthText: {
    fontFamily: 'Inter_300Light',
    fontSize: 12,
    color: theme.buttonPrimary,
  },
  errorContainer: {
    marginTop: 4,
  },
  errorText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: theme.error,
  },
  errorLink: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: theme.error,
    textDecorationLine: 'underline',
  },
  termsText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 10,
    color: theme.textSecondary,
    marginBottom: 24,
    lineHeight: 11.8,
    textAlign: 'center',
  },
  termsTextOrange: {
    fontFamily: 'Inter_400Regular',
    fontSize: 10,
    color: theme.buttonPrimary,
    lineHeight: 11.8,
  },
  submitButton: {
    width: SCREEN_HEIGHT < 700 ? 160 : 180,
    height: SCREEN_HEIGHT < 700 ? 45 : 50,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 'auto',
    marginBottom: SCREEN_HEIGHT < 700 ? 80 : 100,
    alignSelf: 'center',
  },
  submitButtonText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: SCREEN_HEIGHT < 700 ? 15 : 17,
    lineHeight: SCREEN_HEIGHT < 700 ? 15 : 20,
    color: theme.buttonText,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    width: '90%',
    maxWidth: 400,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  successModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  successModalContainer: {
    width: SCREEN_WIDTH * 0.9,
    maxWidth: 400,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  successIcon: {
    marginBottom: 16,
  },
  successTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 22,
    marginBottom: 12,
    textAlign: 'center',
  },
  successMessage: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    marginBottom: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  successButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successButtonText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 16,
  },
});

